Controllers/Reporting/GetPointReportingController.cs
using Microsoft.Reporting.WebForms;
using SaveWedding.Datasets;
using SaveWedding.Models;
using System;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace SaveWedding.Controllers.Reporting
{
    public class GetPointReportingController : Controller
    {
        DBEntities db = new DBEntities();
        PointDataSet ds = new PointDataSet();
        ReportViewer report = new ReportViewer();
        // GET: GetPoint      
        public ActionResult Points(string filter, string idmonth)
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "1")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                report.ProcessingMode = ProcessingMode.Local;
                report.Width = Unit.Pixel(930);
                string queries = "";

                switch (filter)
                {
                    case "1":
                        if (idmonth != null || idmonth != "")
                        {
                            int idmon = Convert.ToInt32(idmonth);
                            queries = "select * from GetPointData where savingstatus IS NULL AND MONTH(uploaddate) =" + idmon;
                        }
                        break;
                    default:
                        queries = "select * from GetPointData";
                        break;
                }
                GetDataPoint(queries);
                var monthdata = db.tblMonths.ToList();
                return View(monthdata);
            }
        }

        public void GetDataPoint(string queries)
        {
            //Connect to Database
            var connectionString = ConfigurationManager.ConnectionStrings["DbSaveWeddingConnectionString"].ConnectionString;
            SqlConnection conn = new SqlConnection(connectionString);
            SqlDataAdapter dataAdapter = new SqlDataAdapter(queries, conn);
            dataAdapter.Fill(ds, ds.GetPointData.TableName);
            //get data report and send to rdlc
            report.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Report\PointReport.rdlc";
            report.LocalReport.DataSources.Clear();
            report.LocalReport.DataSources.Add(new ReportDataSource("DataSetPoint", ds.Tables[0]));
            report.LocalReport.Refresh();
            //save data to viewbag
            ViewBag.PointReportViewer = report;
        }
    }
}

Views/GetPointReporting/Points.cshtml
@using ReportViewerForMvc;
@model IEnumerable<SaveWedding.Models.tblMonth>
@{
    Layout = null;
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white mr-2">
                    <i class="mdi mdi-home"></i>
                </span> Customer Points
            </h3>
        </div>
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Customer Points</h4>
                        <div class="row pb-2 pt-1">
                            <div class="col-12">
                                <div class="input-group-prepend" style="float:right;">
                                    <label style="color:black;width:80px;">Filters By</label>
                                    <button class="btn btn-sm btn-outline-primary dropdown-toggle" style="margin-left:1%;" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Select</button>
                                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 46px, 0px);">
                                        @if (Model != null)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <a class="dropdown-item" href="@Url.Action("Points","GetPointReporting",new {filter=1, idmonth=item.monthid })">@item.monthname</a>
                                            }
                                        }
                                        <a class="dropdown-item" href="@Url.Action("Points","GetPointReporting",new {filter=0 })">All Data</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @if (ViewBag.PointReportViewer != null)
                        {
                            @Html.ReportViewer(ViewBag.PointReportViewer as Microsoft.Reporting.WebForms.ReportViewer)
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- content-wrapper ends -->
    <!-- partial:partials/_footer.html -->
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 <a href="#" target="_blank"> Save Wedding</a>.All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
        </div>
    </footer>
    <!-- partial -->
</div>