Controllers/User/ClaimController.cs
using SaveWedding.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web.Hosting;
using System.Web.Mvc;

namespace SaveWedding.Controllers.User
{
    public class ClaimController : Controller
    {
        DBEntities db = new DBEntities();
        // GET: Claim
        public ActionResult Index()
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "2")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                long iduser = Convert.ToInt64(Session["logedUserId"]);
                List<tblClaim> claimdata = db.tblClaims.Where(x => x.userid == iduser).ToList();

                return View(claimdata);
            }
        }

        public ActionResult EditStatusClaim(long Idclaim, int status)
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "2")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                var claimddata = db.tblClaims.Where(x => x.claimid == Idclaim).SingleOrDefault();

                if (claimddata != null)
                {
                    try
                    {
                        claimddata.claimstatus = 1;
                        claimddata.usedate = DateTime.Now;
                        db.SaveChanges();

                        TempData["message"] = claimddata.tblReward.rewardname + " Used";
                    }
                    catch (Exception error)
                    {
                        throw error;
                    }
                    long claimId = claimddata.claimid;
                    BuildEmailTemplate(claimId);
                }

                return RedirectToAction("Index", "Claim");
            }
        }
        public ActionResult ClaimReward(string rewardpoint, string rewardid)
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "2")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                if (rewardpoint != "")
                {
                    long iduser = Convert.ToInt64(Session["logedUserId"]);

                    var savingdata = db.tblSavings.Where(x => x.userid == iduser).OrderByDescending(x => x.savingid).FirstOrDefault();
                    if (savingdata != null)
                    {
                        var totalpoint = Math.Round(Convert.ToDouble(savingdata.point), 0);
                        tblClaim claim = new tblClaim();
                        int Point = Convert.ToInt32(rewardpoint);
                        long Idreward = Convert.ToInt64(rewardid);
                        if (totalpoint >= Point)
                        {
                            double kurang = totalpoint - Point;
                            claim.userid = iduser;
                            claim.rewardid = Idreward;
                            claim.claimstatus = 0;
                            claim.claimdate = DateTime.Now;
                            db.tblClaims.Add(claim);
                            db.SaveChanges();

                            savingdata.point = kurang;
                            db.SaveChanges();

                            TempData["claimresult"] = "1";
                        }
                        else
                        {
                            TempData["claimresult"] = "2";
                        }
                    }
                    else
                    {
                        TempData["claimresult"] = "2";
                    }
                }
                TempData.Keep();
                return RedirectToAction("Index", "User");
            }
        }

        public void BuildEmailTemplate(long Idclaim)
        {
            string Body = System.IO.File.ReadAllText(HostingEnvironment.MapPath("~/Templates/EmailTemp/") + "UseReward" + ".cshtml");
            var rewardinfo = db.tblClaims.Where(x => x.claimid == Idclaim).FirstOrDefault();

            var datauser = db.tblUsers.Where(x => x.userid == rewardinfo.userid).FirstOrDefault();

            var pointo = rewardinfo.tblReward.totalpoint.Value.ToString("N0");
            Body = Body.Replace("@ViewBag.rewardname", rewardinfo.tblReward.rewardname);
            Body = Body.Replace("@ViewBag.Name", datauser.name);
            Body = Body.Replace("@ViewBag.point", pointo);
            Body = Body.Replace("@ViewBag.usedate", rewardinfo.usedate.Value.ToString("dd/MM/yyyy HH:mm"));
            Body = Body.ToString();
            BuildEmailTemplate("Your Reward Use Confirmation from Save Wedding!", Body, datauser.email);

        }

        public static void BuildEmailTemplate(string SubjectText, string BodyText, string SendTo)
        {
            string from, to, bcc, cc, subject, body;
            from = "saveweddingali@gmail.com";
            to = SendTo.Trim();
            bcc = "";
            cc = "";
            subject = SubjectText;
            StringBuilder sb = new StringBuilder();
            sb.Append(BodyText);
            body = sb.ToString();
            MailMessage mail = new MailMessage();
            mail.From = new MailAddress(from, "Save Wedding");
            mail.To.Add(new MailAddress(to));
            if (!string.IsNullOrEmpty(bcc))
            {
                mail.Bcc.Add(new MailAddress(bcc));
            }
            if (!string.IsNullOrEmpty(cc))
            {
                mail.CC.Add(new MailAddress(cc));
            }
            mail.Subject = subject;
            mail.Body = body;
            mail.IsBodyHtml = true;
            SendEmail(mail);
        }

        public static void SendEmail(MailMessage mail)
        {
            SmtpClient client = new SmtpClient();
            client.Host = "smtp.gmail.com";
            client.Port = 587;
            client.EnableSsl = true;
            client.UseDefaultCredentials = false;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.Credentials = new System.Net.NetworkCredential("saveweddingali@gmail.com", "savewedding123");
            try
            {
                client.Send(mail);
            }
            catch (Exception error)
            {
                throw error;
            }
        }

    }
}

Controllers/User/InformationController.cs
using SaveWedding.Models;
using SaveWedding.Models.Admin;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SaveWedding.Controllers.User
{
    public class InformationController : Controller
    {
        // GET: Information
        DBEntities db = new DBEntities();
        public ActionResult Index()
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "2")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                List<tblPackage> packagedata = db.tblPackages.ToList();
                List<tblItem> itemdata = db.tblItems.ToList();
                List<tblCategory> categorydata = db.tblCategories.ToList();

                PackageItemCategory datalist = new PackageItemCategory();
                datalist.Package = packagedata;
                datalist.Item = itemdata;
                datalist.Category = categorydata;

                return View(datalist);
            }

        }
    }
}

Controllers/User/SimulationController.cs
using SaveWedding.Models;
using SaveWedding.Models.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SaveWedding.Controllers.User
{
    public class SimulationController : Controller
    {
        // GET: Simulation
        DBEntities db = new DBEntities();
        public ActionResult Index()
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "2")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                List<tblSalary> salarydata = db.tblSalaries.ToList();
                List<tblCity> citydata = db.tblCities.ToList();
                List<tblJob> jobdata = db.tblJobs.ToList();
                List<tblUser> userdata = db.tblUsers.ToList();


                JobSalaryCityUser datalist = new JobSalaryCityUser();
                datalist.Salary = salarydata;
                datalist.City = citydata;
                datalist.Job = jobdata;
                datalist.User = userdata;

                return View(datalist);
            }


        }

        public JsonResult CountSimulation(string city, string salary, string proffesion)
        {
            var data = db.tblPackages.Select(x => x.packagename).ToArray();
            string[] saran = new string[4];
            string finalresult = "";
            string paramage = Request.Params["age"];
            if (data != null)
            {
                int age = Convert.ToInt32(paramage);
                //validasi salary
                string[] packagelist = data;
                if (salary == "7")
                {
                    saran[0] = packagelist[0];
                }
                else if (salary == "8")
                {
                    saran[0] = packagelist[1];
                }
                else
                {
                    saran[0] = packagelist[2];
                }

                //validasi profesi
                if (proffesion == "1")
                {
                    saran[1] = packagelist[0];
                }
                else if (proffesion == "3" || proffesion == "4")
                {
                    saran[1] = packagelist[1];
                }
                else
                {
                    saran[1] = packagelist[2];
                }

                //validasi city
                if (city == "1159" || city == "1162")
                {
                    saran[2] = packagelist[2];
                }
                else if (city == "1160" || city == "1161" || city == "1163")
                {
                    saran[2] = packagelist[1];
                }
                else
                {
                    saran[2] = packagelist[0];
                }

                //validasi age
                if (age >= 18 && age <= 25)
                {
                    saran[3] = packagelist[0];
                }
                else if (age >= 26 && age <= 33)
                {
                    saran[3] = packagelist[1];
                }
                else
                {
                    saran[3] = packagelist[2];
                }

                if (saran != null)
                {
                    int paket1 = 0;
                    int paket2 = 0;
                    string hasil = saran[0];
                    string hasil2 = saran[1];

                    foreach (string item in saran)
                    {
                        if (item == hasil)
                        {
                            paket1 += 1;
                            if (paket1 >= 2)
                            {
                                finalresult = item;
                                break;
                            }
                        }
                        else if (item == hasil2)
                        {
                            paket2 += 1;
                            if (paket2 >= 2)
                            {
                                finalresult = item;
                                break;
                            }
                        }
                        else
                        {
                            finalresult = packagelist[1];


                        }
                    }
                }
            }


            return Json(finalresult, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/User/ChangePassword.cshtml
@model SaveWedding.Models.tblUser
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="~/Templates/PurpleTemp/assets/images/logo.svg" />
    <title>Save Wedding</title>
    @Styles.Render("~/bundles/Signupcss")
</head>
<body>

    <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
            <img src="~/Templates/PurpleTemp/assets/images/zikri-04.svg" style="margin-left:40%;" alt="logo Save Wedding" />
        </div>
    </nav>

    <div class="container-fluid">
        <div class="container-fluid page-body-wrapper full-page-wrapper">

            <div class="content-wrapper d-flex align-items-center auth">

                <div class="row flex-grow">
                    <div class="col-lg-6 mx-auto">
                        <h2 style="text-align:center">Change Password</h2><br />
                        <div class="auth-form-light text-left p-2">
                            <form class="pt-3" method="post">
                                <div id="Message1">
                                    @if (TempData["success"] != null)
                                    {
                                        <label id="labelchangepassword" class="alert-success"><strong>@TempData["success"]</strong></label>

                                    }
                                    <label class="alert-success"><strong>@TempData["error"]</strong></label>
                                </div>                                
                                <div class="form-group">
                                    @*<input type="password" class="form-control form-control-lg" placeholder=" Old Password" minlength="6" required="required">*@
                                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @type = "password", @class = "form-control form-control-lg", @placeholder = "Old Password", @minlength = "6", @required = "required" } })
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control form-control-lg" name="Kode" id="InputPassword" placeholder=" New Password" minlength="6" required="required">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control form-control-lg password" name="Kode2" id="InputPassword2" placeholder="Repeat Password" minlength="6" required="required">
                                    <div id="Message2">
                                    </div>
                                </div>
                                <div class="form-group">
                                    @* <button id="BtnSignUp" class="btn btn-primary mb-4 font-weight-medium auth-form-btn" data-toggle="modal" data-target="#ChangePasswordModal" style="float:right;">Save</button>*@
                                    <button id="BtnSignUp" class="btn btn-primary mb-4 font-weight-medium auth-form-btn" style="float:right; margin-top: 1rem;">Save</button>
                                    <a href="@Url.Action("Index","User")"  class="btn btn-secondary mb-4 font-weight-medium auth-form-btn" style="float:right; margin-right: 1rem; margin-top: 1rem;">Cancel</a>
                                </div>
                            </form>
                        </div><br />

                    </div>
                </div>
            </div>
        </div>
    </div>
  

    @Scripts.Render("~/Content/Signupjs")
    <script>


        $('.password').keyup(function () {
            if ($('#InputPassword').val() != $('#InputPassword2').val()) {
                $('#Message2').html(' <label class="alert-danger"><strong>Your password and Repeat password donot match!</strong></label>');
                $('#BtnSignUp').attr('type', 'button');
            } else {
                $('#Message2').html("");
                $('#BtnSignUp').attr('type', 'submit');
            }
        });


     
        var d = $('#labelchangepassword').text();
        if (d != "") {
            alert(d);
            window.location.href = "@Url.Action("Index","User")";          
        } 
    </script>
</body>
</html>

Views/User/ClaimReward.cshtml
<!-- Modal -->
@if (Model.Reward != null)
{
    var activecarousel = 1;
    foreach (var reward in Model.Reward)
    {
        <div class="modal fade" id="ClaimRewardModal_@activecarousel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">                      
                            <h4 style="text-align:center;">Are You Sure want to Claim @reward.rewardname?</h4>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>                       
                        @Html.ActionLink("Yes","ClaimReward","Claim",new {rewardid=reward.rewardid, rewardpoint=reward.totalpoint},new { @class="btn btn-danger"})
                    </div>
                </div>
            </div>
        </div>
        activecarousel++;
    }
}

Views/User/IklanSimulasi.cshtml
<div class="modal fade" id="iklansimulasi" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document" style="width:65%; height:100%;">
        <div class="modal-content">
            <div class="modal-body" style="background:url(@Url.Content("~/Templates/HomeTemp/images/swbn-01-02.jpg"));background-size:100%;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="width:10%;margin-left:90%;">
                    <span aria-hidden="true">Close(&times;)</span>
                </button>
                <h1 style="color:white; font-family:'Arial Rounded MT';text-align:center;">

                    <b>Hello @Session["logedUsername"]</b>
                    <br /> <b>Are You Confused for Choosing Your Planning Package in Marriage?</b>

                </h1>
                <h3 style="color:white;text-align:center;">
                    <strong>
                        <br /><small>
                            tell us your personal data,
                            then we will help you finding a Suitable Package for You in
                        </small>Simulation.
                    </strong>
                </h3>
                <a href="@Url.Action("Index","Simulation")" class="btn btn-outline-primary btn-icon-text" style="float:right;">
                    <i class="mdi mdi-play-circle btn-icon-prepend mdi-36px"></i>
                    <span class="d-inline-block text-left" style="color:white;">
                        <small class="font-weight-light d-block">Let's Get</small> Started
                    </span>
                </a>
            </div>

        </div>
    </div>
</div>

Views/User/Index.cshtml
@model SaveWedding.Models.Admin.RewardItem
@using System.Linq;
@{
    Layout = null;
    Layout = "~/Views/Layout/_UserLayout.cshtml";

}

@Scripts.Render("~/Content/jquery")
@*@Scripts.Render("~/Content/carousel")*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<style>
    /* Make the image fully responsive */
    .carousel-inner img {
        width: 100%;
        height: 100%;
    }
</style>
<title>Save Wedding</title>
<div class="main">
    <div class="content-wrapper">
        <div class="row" id="proBanner">
            <div class="col-12">
            </div>
        </div>
        <div class="page-header">
            <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white mr-2">
                    <i class="mdi mdi-home"></i>
                </span> Home
            </h3>
        </div>
        <div class="row">
            @if (Model.Reward != null)
            {
                <div class="col-md-12 stretch-card grid-margin">
                    <div class="card">
                        <div id="demo" class="carousel slide" data-ride="carousel">
                            <ul class="carousel-indicators">
                                <li data-target="#demo" data-slide-to="0" class="active"></li>
                                <li data-target="#demo" data-slide-to="1"></li>
                                <li data-target="#demo" data-slide-to="2"></li>
                            </ul>
                            <div class="carousel-inner">
                                @{ var activecarousel = 1;}
                                @foreach (var reward in Model.Reward)
                                {
                                    if (reward.status == 1)
                                    {
                                    <div class="carousel-item @(activecarousel == 1 ? Html.Raw("active") : Html.Raw(""))">
                                        <img src="@Url.Content(reward.imagebanner)" alt="Reward Points" width="402" height="125">
                                        <div class="carousel-caption">
                                            <h3>@reward.totalpoint.Value.ToString("N0") Points</h3>
                                            <p id="contentajha">@reward.rewardname</p>
                                            <a href="#" class="btn btn-rounded btn-outline-warning mb-auto font-weight-medium btn-lg" data-toggle="modal" data-target="#ClaimRewardModal_@activecarousel">
                                                Claim
                                            </a>
                                        </div>
                                    </div>
                                        activecarousel++;
                                    }
                                }

                            </div>
                            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                                <span class="carousel-control-prev-icon"></span>
                            </a>
                            <a class="carousel-control-next" href="#demo" data-slide="next">
                                <span class="carousel-control-next-icon"></span>
                            </a>
                        </div>
                    </div>
                </div>
            }

            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Recent Update Items</h4><br />
                            <div class="row mt-3">
                                <div class="col-6 pr-1">
                                    @if (Model.Item != null)
                                    {

                                        <img src="@Url.Content(Model.Item.Where(x => x.categoryid == 1).OrderByDescending(x => x.itemid).FirstOrDefault().itemimage)" class="mb-2 w-100 rounded" width="465" height="400" alt="image">
                                        <img src="@Url.Content(Model.Item.Where(x => x.categoryid == 4).OrderByDescending(x => x.itemid).FirstOrDefault().itemimage)" class="mb-2 w-100 rounded" width="465" height="400" alt="image">

                                    }
                                </div>
                                <div class="col-6 pr-1">
                                    @if (Model.Item != null)
                                    {

                                        <img src="@Url.Content(Model.Item.Where(x => x.categoryid == 2).OrderByDescending(x => x.itemid).FirstOrDefault().itemimage)" class="mb-2 w-100 rounded" width="465" height="400" alt="image">
                                        <img src="@Url.Content(Model.Item.Where(x => x.categoryid == 3).OrderByDescending(x => x.itemid).FirstOrDefault().itemimage)" class="mb-2 w-100 rounded" width="465" height="400" alt="image">


                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- content-wrapper ends -->
    <!-- partial:partials/_footer.html -->
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 <a href="#" target="_blank"> Save Wedding</a>.All rights reserved.</span>
        </div>
        <input type="hidden" value="@TempData["iklansimulasi"]" id="iklansimulation" />
        <input type="hidden" value="@TempData["claimresult"]" id="claimresult" />
    </footer>
    <!-- partial -->
</div>

@Scripts.Render("~/Content/jquery")

@Html.Partial("~/Views/User/IklanSimulasi.cshtml")
@Html.Partial("ClaimReward")
@Html.Partial("~/Views/User/WarningModal.cshtml")
<script>
    var nilaiiklan = $('#iklansimulation').val();
    if (nilaiiklan == "1") {
        setTimeout(function () {
            $('#iklansimulasi').modal({ backdrop: 'static', keyboard: false, show: true });
        }, 800);
    }

    $(document).ready(function () { 
    var viewbagclaim = $('#claimresult').val();
        if (viewbagclaim == "1") {
            var urlhere = "<a href='@Url.Action("Index","Claim")' style='color:blue;'>Here</a>";
            var warning = "<h5 class='alert alert-success'>Your Points is Success to be changed! Please Click " +
                urlhere + " to see All Your Vouchers</h5>";
            $('#warningmodals .modal-body').html(warning);
            $('#warningmodals').modal('show');
        } else if (viewbagclaim == "2") {
            var warning = "<h5 class='alert alert-danger'>Your Points are not Enough for Claim this Voucher!</h5>";
            $('#warningmodals .modal-body').html(warning);
            $('#warningmodals').modal('show');
        } else if (viewbagclaim == "0") {
            var warning = "<h5 class='alert alert-danger'>Something Went Wrong!</h5>";
            $('#warningmodals .modal-body').html(warning);
            $('#warningmodals').modal('show');
        } else {
            $('#warningmodals').modal('hide');
        }
        });
</script>

Views/User/WarningModal.cshtml
<div class="modal fade" id="warningmodals" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document" style="width:65%;">
        <div class="modal-content">
            <div class="modal-header"> 
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>