Controllers/Reporting/ClaimRewardReportingController.cs
using Microsoft.Reporting.WebForms;
using SaveWedding.Datasets;
using SaveWedding.Models;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace SaveWedding.Controllers.Reporting
{
    public class ClaimRewardReportingController : Controller
    {
        DBEntities db = new DBEntities();
        ClaimRewardDataSet ds = new ClaimRewardDataSet();
        ReportViewer report = new ReportViewer();
        // GET: ClaimReward
        public ActionResult Claims(string filter)
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "1")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                report.ProcessingMode = ProcessingMode.Local;
                report.Width = Unit.Pixel(930);
                string queries = "";

                switch (filter)
                {
                    case "1":
                        queries = "select * from ClaimRewardData where claimstatus =" + 1;
                        break;
                    case "2":
                        queries = "select * from ClaimRewardData where claimstatus =" + 0;
                        break;
                    default:
                        queries = "select * from ClaimRewardData";
                        break;
                }
                GetDataClaim(queries);

                return View();
            }
        }

        public void GetDataClaim(string queries)
        {
            //Connect to Database
            var connectionString = ConfigurationManager.ConnectionStrings["DbSaveWeddingConnectionString"].ConnectionString;
            SqlConnection conn = new SqlConnection(connectionString);
            SqlDataAdapter dataAdapter = new SqlDataAdapter(queries, conn);
            dataAdapter.Fill(ds, ds.ClaimRewardData.TableName);
            //get data report and send to rdlc
            report.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Report\ClaimRewardReport.rdlc";
            report.LocalReport.DataSources.Clear();
            report.LocalReport.DataSources.Add(new ReportDataSource("DataSetClaim", ds.Tables[0]));
            report.LocalReport.Refresh();
            //save data to viewbag
            ViewBag.ClaimReportViewer = report;
        }
    }
}

Controllers/User/ClaimController.cs
using SaveWedding.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web.Hosting;
using System.Web.Mvc;

namespace SaveWedding.Controllers.User
{
    public class ClaimController : Controller
    {
        DBEntities db = new DBEntities();
        // GET: Claim
        public ActionResult Index()
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "2")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                long iduser = Convert.ToInt64(Session["logedUserId"]);
                List<tblClaim> claimdata = db.tblClaims.Where(x => x.userid == iduser).ToList();

                return View(claimdata);
            }
        }

        public ActionResult EditStatusClaim(long Idclaim, int status)
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "2")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                var claimddata = db.tblClaims.Where(x => x.claimid == Idclaim).SingleOrDefault();

                if (claimddata != null)
                {
                    try
                    {
                        claimddata.claimstatus = 1;
                        claimddata.usedate = DateTime.Now;
                        db.SaveChanges();

                        TempData["message"] = claimddata.tblReward.rewardname + " Used";
                    }
                    catch (Exception error)
                    {
                        throw error;
                    }
                    long claimId = claimddata.claimid;
                    BuildEmailTemplate(claimId);
                }

                return RedirectToAction("Index", "Claim");
            }
        }
        public ActionResult ClaimReward(string rewardpoint, string rewardid)
        {
            string actorids = Session["logedActorId"].ToString();
            if (Session["logedEmail"] == null || Session["logedUserImage"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (actorids != "2")
            {
                return RedirectToAction("PermissionAccess", "Home");
            }
            else
            {
                if (rewardpoint != "")
                {
                    long iduser = Convert.ToInt64(Session["logedUserId"]);

                    var savingdata = db.tblSavings.Where(x => x.userid == iduser).OrderByDescending(x => x.savingid).FirstOrDefault();
                    if (savingdata != null)
                    {
                        var totalpoint = Math.Round(Convert.ToDouble(savingdata.point), 0);
                        tblClaim claim = new tblClaim();
                        int Point = Convert.ToInt32(rewardpoint);
                        long Idreward = Convert.ToInt64(rewardid);
                        if (totalpoint >= Point)
                        {
                            double kurang = totalpoint - Point;
                            claim.userid = iduser;
                            claim.rewardid = Idreward;
                            claim.claimstatus = 0;
                            claim.claimdate = DateTime.Now;
                            db.tblClaims.Add(claim);
                            db.SaveChanges();

                            savingdata.point = kurang;
                            db.SaveChanges();

                            TempData["claimresult"] = "1";
                        }
                        else
                        {
                            TempData["claimresult"] = "2";
                        }
                    }
                    else
                    {
                        TempData["claimresult"] = "2";
                    }
                }
                TempData.Keep();
                return RedirectToAction("Index", "User");
            }
        }

        public void BuildEmailTemplate(long Idclaim)
        {
            string Body = System.IO.File.ReadAllText(HostingEnvironment.MapPath("~/Templates/EmailTemp/") + "UseReward" + ".cshtml");
            var rewardinfo = db.tblClaims.Where(x => x.claimid == Idclaim).FirstOrDefault();

            var datauser = db.tblUsers.Where(x => x.userid == rewardinfo.userid).FirstOrDefault();

            var pointo = rewardinfo.tblReward.totalpoint.Value.ToString("N0");
            Body = Body.Replace("@ViewBag.rewardname", rewardinfo.tblReward.rewardname);
            Body = Body.Replace("@ViewBag.Name", datauser.name);
            Body = Body.Replace("@ViewBag.point", pointo);
            Body = Body.Replace("@ViewBag.usedate", rewardinfo.usedate.Value.ToString("dd/MM/yyyy HH:mm"));
            Body = Body.ToString();
            BuildEmailTemplate("Your Reward Use Confirmation from Save Wedding!", Body, datauser.email);

        }

        public static void BuildEmailTemplate(string SubjectText, string BodyText, string SendTo)
        {
            string from, to, bcc, cc, subject, body;
            from = "saveweddingali@gmail.com";
            to = SendTo.Trim();
            bcc = "";
            cc = "";
            subject = SubjectText;
            StringBuilder sb = new StringBuilder();
            sb.Append(BodyText);
            body = sb.ToString();
            MailMessage mail = new MailMessage();
            mail.From = new MailAddress(from, "Save Wedding");
            mail.To.Add(new MailAddress(to));
            if (!string.IsNullOrEmpty(bcc))
            {
                mail.Bcc.Add(new MailAddress(bcc));
            }
            if (!string.IsNullOrEmpty(cc))
            {
                mail.CC.Add(new MailAddress(cc));
            }
            mail.Subject = subject;
            mail.Body = body;
            mail.IsBodyHtml = true;
            SendEmail(mail);
        }

        public static void SendEmail(MailMessage mail)
        {
            SmtpClient client = new SmtpClient();
            client.Host = "smtp.gmail.com";
            client.Port = 587;
            client.EnableSsl = true;
            client.UseDefaultCredentials = false;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.Credentials = new System.Net.NetworkCredential("saveweddingali@gmail.com", "savewedding123");
            try
            {
                client.Send(mail);
            }
            catch (Exception error)
            {
                throw error;
            }
        }

    }
}

Views/ClaimRewardReporting/Claims.cshtml
@using ReportViewerForMvc;
@{
    Layout = null;
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white mr-2">
                    <i class="mdi mdi-home"></i>
                </span> Claim Reward
            </h3>
        </div>
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Claim Reward</h4>
                        <div class="row pb-2 pt-1">
                            <div class="col-12">
                                <div class="input-group-prepend" style="float:right;">
                                    <label style="color:black;width:80px;">Filters By</label>
                                    <button class="btn btn-sm btn-outline-primary dropdown-toggle" style="margin-left:1%;" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Select</button>
                                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 46px, 0px);">
                                        <a class="dropdown-item" href="@Url.Action("Claims","ClaimRewardReporting",new {filter=1 })">Applied</a>
                                        <a class="dropdown-item" href="@Url.Action("Claims","ClaimRewardReporting",new {filter=2 })">Not Applied</a>
                                        <a class="dropdown-item" href="@Url.Action("Claims","ClaimRewardReporting",new {filter=0 })">All Data</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @if (ViewBag.ClaimReportViewer != null)
                        {
                            @Html.ReportViewer(ViewBag.ClaimReportViewer as Microsoft.Reporting.WebForms.ReportViewer)
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- content-wrapper ends -->
    <!-- partial:partials/_footer.html -->
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 <a href="#" target="_blank"> Save Wedding</a>.All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
        </div>
    </footer>
    <!-- partial -->
</div>